
package geekbrains.soap;


import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapServiceService", targetNamespace = "http://soap.geekbrains.ru/", wsdlLocation = "http://localhost:8080/firstapp/SoapService?wsdl")
public class SoapServiceService
    extends Service
{

    private final static URL SOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICESERVICE_EXCEPTION;
    private final static QName SOAPSERVICESERVICE_QNAME = new QName("http://soap.geekbrains.ru/", "SoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/firstapp/SoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICESERVICE_WSDL_LOCATION = url;
        SOAPSERVICESERVICE_EXCEPTION = e;
    }

    public SoapServiceService() {
        super(__getWsdlLocation(), SOAPSERVICESERVICE_QNAME);
    }

    public SoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICESERVICE_QNAME, features);
    }

    public SoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICESERVICE_QNAME);
    }

    public SoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICESERVICE_QNAME, features);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "SoapServicePort")
    public WebServiceInterface getSoapServicePort() {
        return super.getPort(new QName("http://soap.geekbrains.ru/", "SoapServicePort"), WebServiceInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "SoapServicePort")
    public WebServiceInterface getSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.geekbrains.ru/", "SoapServicePort"), WebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPSERVICESERVICE_EXCEPTION;
        }
        return SOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
