
package geekbrains.soap;


import geekbrains.service.CategoryDTO;
import geekbrains.service.ObjectFactory;
import geekbrains.service.ProductDTO;

import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://service.geekbrains.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     * @return
     *     returns java.util.List<ru.geekbrains.service.ProductDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetAllProductsResponse")
    public List<ProductDTO> getAllProducts();

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.geekbrains.service.ProductDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProductResponse")
    public ProductDTO getProduct(
			@WebParam(name = "arg0", targetNamespace = "")
					long arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeProduct", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.RemoveProduct")
    @ResponseWrapper(localName = "removeProductResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.RemoveProductResponse")
    public void removeProduct(
			@WebParam(name = "arg0", targetNamespace = "")
					long arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns ru.geekbrains.service.ProductDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductByTitle", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProductByTitle")
    @ResponseWrapper(localName = "getProductByTitleResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProductByTitleResponse")
    public ProductDTO getProductByTitle(
			@WebParam(name = "arg0", targetNamespace = "")
					String arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.AddProductResponse")
    public void addProduct(
			@WebParam(name = "arg0", targetNamespace = "")
					ProductDTO arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<ru.geekbrains.service.ProductDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.GetProductsResponse")
    public List<ProductDTO> getProducts(
			@WebParam(name = "arg0", targetNamespace = "")
					long arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCategory", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.AddCategory")
    @ResponseWrapper(localName = "addCategoryResponse", targetNamespace = "http://service.geekbrains.ru/", className = "ru.geekbrains.service.AddCategoryResponse")
    public void addCategory(
			@WebParam(name = "arg0", targetNamespace = "")
					CategoryDTO arg0);

}
